require_relative 'test_helper'

module Plasma
  # Proves the Ruby port reproduces the original prototype's logic exactly.
  #
  # The fixture in prototype_parity.json was generated by executing the
  # prototype's own JavaScript (genWave, storyMediaType, genAnnotations) and
  # dumping the results. If a port ever drifts, these fail -- which matters
  # because the shell still draws waveforms client-side and must agree with
  # the peaks the server computes.
  class ParityTest < TestCase
    FIXTURE = JSON.parse(File.read(File.expand_path('prototype_parity.json', __dir__)))

    def test_waveform_matches_the_javascript_implementation
      FIXTURE['waves'].each do |seed, expected|
        actual = Waveform.generate(120, seed.to_i)

        assert_equal expected.length, actual.length, "wrong sample count for seed #{seed}"
        expected.each_with_index do |value, i|
          assert_in_delta value, actual[i], 1e-12,
                          "sample #{i} diverged for seed #{seed}"
        end
      end
    end

    def test_media_type_matches_the_javascript_implementation
      FIXTURE['media'].each do |key, expected|
        cat_index, rec_index = key.split('-').map(&:to_i)
        recording = archive.category(cat_index).recording(rec_index)

        assert_equal expected, recording.media_type,
                     "media type diverged for #{recording.title.inspect}"
      end
    end

    def test_seeded_annotations_match_the_javascript_implementation
      FIXTURE['annotations'].each do |key, expected|
        cat_index, rec_index = key.split('-').map(&:to_i)
        actual = archive.category(cat_index).recording(rec_index).seeded_annotations

        assert_equal expected.length, actual.length, "annotation count diverged for #{key}"

        expected.each_with_index do |ann, i|
          assert_in_delta ann['pos'], actual[i][:position], 1e-12, "position diverged for #{key}[#{i}]"
          assert_equal ann['catIdx'], actual[i][:category_index], "tag diverged for #{key}[#{i}]"
          assert_equal ann['label'], actual[i][:label], "label diverged for #{key}[#{i}]"
        end
      end
    end

    # The fixture is only meaningful if it actually covers the archive.
    def test_fixture_covers_every_recording
      assert_equal archive.recordings.length, FIXTURE['media'].length
      assert_equal archive.recordings.length, FIXTURE['annotations'].length
    end
  end
end
